apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: eeldsqu2q-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-6c2e12c45e.6lpa.p3.openshiftapps.com/rhtap/rhtap-qe:320119cf8db0536e6e1f95bfc280be1b28ff7622@sha256:a22dce4464eb9ed4b84e3b1de45aaaf950e507552345eebc1a2ec5968197acac
          name: container-image
